[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pixelscan-image-compressor"
version = "0.1.2.0"
description = "Pixel scanning row-column image compressor and decompressor with CustomTkinter Desktop GUI"
readme = "README.md"
authors = [
    { name = "Hasitha Wijesinghe", email = "hasithalwi@github.com" }
]
license = { text = "MIT" }
requires-python = ">=3.10"
dependencies = [
    "Pillow>=10.0.0",
    "customtkinter>=6.0.0",
]

[project.urls]
Homepage = "https://github.com/HasithaLWi"
Repository = "https://github.com/HasithaLWi/img-cmp-python"

[project.scripts]
image-compressor = "src.my_app.main:main"

